### ISSUE TITLE
Cloning Seaside-Legacy30 consistently signals an IceGenericError while ‘git clone’ works

### ISSUE THREAD

**Issue by Rinzwind** [npasserini/iceberg#1600]
Cloning https://github.com/SeasideSt/Seaside-Legacy30 signals an IceGenericError, the message text is either ‘error reading from the zlib stream’ or ‘bad packet length’:

```
(MCGitHubRepository location: 'github://SeasideSt/Seaside-Legacy30/repository') getOrCreateIcebergRepository
```

I tried running the following Bash script a few times, the `git clone` command always passed, but the Pharo command failed each time with the IceGenericError.

```bash
#!/bin/bash

pharovm=~/'Documents/Pharo/vms/110-x64/Pharo.app/Contents/MacOS/Pharo'
pharoimage=~/'Documents/Pharo/images/Pharo 11.0 - 64bit (development version, latest)/Pharo 11.0 - 64bit (development version, latest).image'

cd "$(mktemp -d)" &&
git clone 'https://github.com/SeasideSt/Seaside-Legacy30.git' &&
"${pharovm}" --headless "${pharoimage}" eval "(MCGitHubRepository location: 'github://SeasideSt/Seaside-Legacy30/repository') getOrCreateIcebergRepository"
```

**Comment by Rinzwind** [comment]
Version numbers:

```
"${pharovm}" --headless "${pharoimage}" eval 'Smalltalk vm version , String lf , SystemVersion current asString'
```

Outputs:

```
'CoInterpreter * VMMaker-tonel.1 uuid: 9bb1c8f0-799d-0d00-a873-c9210f2acd2a Jun 10 2022
StackToRegisterMappingCogit * VMMaker-tonel.1 uuid: 9bb1c8f0-799d-0d00-a873-c9210f2acd2a Jun 10 2022
v9.0.15 - Commit: b4879008 - Date: 2022-06-02 09:48:57 +0200
Pharo-11.0.0+build.139.sha.a27ce95057ccbf882eb5edd852f7ba46f22aad90 (64 Bit)'
```

**Comment by JanBliznicenko** [comment]
I have the same error with linux and mac CI. The CI completely stopped working. Win seems unaffected

**Comment by Rinzwind** [comment]
This is probably due to a bug which was fixed in libgit2 v1.0.1, but Pharo is still using v1.0.0, for more details see: https://github.com/pharo-project/pharo/issues/11481#issuecomment-1201163105.

**Comment by JanBliznicenko** [comment]
@Rinzwind it should be fixed now, try checking again

**Comment by Rinzwind** [comment]
Works in Pharo 11! It still fails in Pharo 9 though, presumably because the result of `LGitLibrary uniqueInstance version` is still `#(1 0 0)`. But I will close this issue as the main discussion is in the linked Pharo issue (https://github.com/pharo-project/pharo/issues/11481).

**Comment by JanBliznicenko** [comment]
Unfortunately, I no longer have any larger Pharo 9 compatible project to test it. Try asking in the main issue discussion - it should have been backported for Pharo 9.
