### ISSUE TITLE
Error: OFFSET_PRIM_CREDTYPE is already used as a variable name in class LGitCredentialsPlaintext

### ISSUE THREAD

**Issue by Uko** [npasserini/iceberg#290]
When trying to push, I get the following error: `Error: OFFSET_PRIM_CREDTYPE is already used as a variable name in class LGitCredentialsPlaintext` after entering credentials.

Here is the stack trace:

```
LGitCredentials class(Object)>>error:
[ :subclass | 
(subclass bindingOf: symbol)
	ifNotNil: [ ^ self
			error:
				symbol asString , ' is already used as a variable name in class '
					, subclass name ] ] in LGitCredentials class(Class)>>addClassVariable: in Block: [ :subclass | ...
OrderedCollection>>do:
LGitCredentials class(Class)>>addClassVariable:
LGitCredentials class(Class)>>addClassVarNamed:
LGitCredentials class(FFIExternalStructure class)>>defineFieldOffset:value:
[ :fieldName :type | 
offset := offset alignedTo: type typeAlignment.
self defineFieldOffset: fieldName value: offset + 1.
(defineBoolean and: [ fieldName isSymbol ])
	ifTrue: [ self defineFieldAccessorsFor: fieldName type: type ].
offset := offset + type typeSize.
externalStructureAlignment := externalStructureAlignment
	max: type typeAlignment ] in LGitCredentials class(FFIExternalStructure class)>>compileFields:withAccessors: in Block: [ :fieldName :type | ...
[ :each | aBlock value: each value: (self at: each) ] in OrderedDictionary>>keysAndValuesDo: in Block: [ :each | aBlock value: each value: (self at: each...etc...
OrderedDictionary>>keysDo:
OrderedDictionary>>keysAndValuesDo:
FFIExternalStructureFieldSpec>>fieldsAndTypesDo:
LGitCredentials class(FFIExternalStructure class)>>compileFields:withAccessors:
LGitCredentials class(ExternalStructure class)>>compileFields:
LGitCredentials class(ExternalStructure class)>>compileFields
LGitCredentials class(ExternalStructure class)>>compiledSpec
ExternalType>>newReferentClass:
ExternalType class>>newTypeNamed:force:
ExternalType class>>structTypeNamed:
FFIExternalStructureType>>externalType
FFIExternalStructureType(FFIExternalType)>>externalTypeWithArity
ByteSymbol(Symbol)>>value:
OrderedCollection>>collect:
LGitSafeFFICalloutMethodBuilder(FFICalloutMethodBuilder)>>createFFICalloutLiteralFromSpec:
LGitSafeFFICalloutMethodBuilder(FFICalloutMethodBuilder)>>generateFFICallout:spec:
LGitSafeFFICalloutMethodBuilder>>generateFFICallout:spec:
[ :builder | self generateFFICallout: builder spec: functionSpec ] in LGitSafeFFICalloutMethodBuilder(FFICalloutMethodBuilder)>>generateMethodFromSpec: in Block: [ :builder | self generateFFICallout: builder spec...etc...
IRBuilder class>>buildIR:
LGitSafeFFICalloutMethodBuilder(FFICalloutMethodBuilder)>>generateMethodFromSpec:
LGitSafeFFICalloutMethodBuilder(FFICalloutMethodBuilder)>>generate
LGitSafeFFICalloutMethodBuilder(FFICalloutMethodBuilder)>>build:

```

**Comment by estebanlm** [comment]
that's not a problem of iceberg but the latest version of UFFI. 
Now... I thought that was fixed so I will need to take a look...

**Comment by estebanlm** [comment]
can you verify you have latests UFFI?

**Comment by demarey** [comment]
I just got the same error with  image #60417.
It does not look to be fixed in latest UFFI

**Comment by estebanlm** [comment]
downloaded latest image, installed iceberg and executed
```Smalltalk
FFIExternalStructure allSubclassesDo: #rebuildFieldAccessors.
```
and everything looks fine, so yes, it is fixed :)
now, what can happen is a weird path that is not covered.

**Comment by demarey** [comment]
I just downloaded a fresh Pharo 6 image #60417, installed dev-04 of iceberg, and executed ```FFIExternalStructure allSubclassesDo: #rebuildFieldAccessors``` .
I declare a new local repository, try to commit and push, and I still get the error.

Here is the VM version I use:
'CoInterpreter VMMaker.oscog-eem.1855 uuid: d8e4a3c2-a3bf-4adc-b224-8012903a1ef4 May  4 2016
StackToRegisterMappingCogit VMMaker.oscog-eem.1855 uuid: d8e4a3c2-a3bf-4adc-b224-8012903a1ef4 May  4 2016
https://github.com/pharo-project/pharo-vm.git Commit: b8ec25a570d7539653e1d793e97609adb509aaed Date: 2016-05-04 11:14:22 +0200 By: Esteban Lorenzano <estebanlm@gmail.com> Jenkins build #589
'

**Comment by estebanlm** [comment]
your VM is severely outdated

**Comment by estebanlm** [comment]
oops didn't meant to close it :P

**Comment by JurajKubelka** [comment]
It works for me in:

```
Image
-----
Pharo6.0
Latest update: #60419
Unnamed

Virtual Machine
---------------
/Users/jura/Documents/PharoVMs/PharoVM70.app/Contents/MacOS/Pharo
CoInterpreter * VMMaker.oscog-EstebanLorenzano.2136 uuid: 40534c32-ca6b-4e97-91ec-31d509e49b0c Mar  1 2017
StackToRegisterMappingCogit * VMMaker.oscog-EstebanLorenzano.2136 uuid: 40534c32-ca6b-4e97-91ec-31d509e49b0c Mar  1 2017
VM: 201703010941 https://github.com/pharo-project/pharo-vm.git $ Date: Wed Mar 1 10:41:59 2017 +0100 $ Plugins: 201703010941 https://github.com/pharo-project/pharo-vm.git $

Mac OS X built on Mar  1 2017 10:16:05 UTC Compiler: 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)
VMMaker versionString VM: 201703010941 https://github.com/pharo-project/pharo-vm.git $ Date: Wed Mar 1 10:41:59 2017 +0100 $ Plugins: 201703010941 https://github.com/pharo-project/pharo-vm.git $
CoInterpreter * VMMaker.oscog-EstebanLorenzano.2136 uuid: 40534c32-ca6b-4e97-91ec-31d509e49b0c Mar  1 2017
StackToRegisterMappingCogit * VMMaker.oscog-EstebanLorenzano.2136 uuid: 40534c32-ca6b-4e97-91ec-31d509e49b0c Mar  1 2017
```

**Comment by JurajKubelka** [comment]
Using the same image for a while, I have similar issue.

System Info:
```
Image
-----
/Users/jura/Library/Application Support/Pharo/images/Pharo Sprint App 03-01/Pharo Sprint App 03-01.image
Pharo6.0
Latest update: #60419
Unnamed

Virtual Machine
---------------
/Users/jura/Documents/PharoVMs/PharoVM70.app/Contents/MacOS/Pharo
CoInterpreter * VMMaker.oscog-EstebanLorenzano.2136 uuid: 40534c32-ca6b-4e97-91ec-31d509e49b0c Mar  1 2017
StackToRegisterMappingCogit * VMMaker.oscog-EstebanLorenzano.2136 uuid: 40534c32-ca6b-4e97-91ec-31d509e49b0c Mar  1 2017
VM: 201703010941 https://github.com/pharo-project/pharo-vm.git $ Date: Wed Mar 1 10:41:59 2017 +0100 $ Plugins: 201703010941 https://github.com/pharo-project/pharo-vm.git $

Mac OS X built on Mar  1 2017 10:16:05 UTC Compiler: 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)
VMMaker versionString VM: 201703010941 https://github.com/pharo-project/pharo-vm.git $ Date: Wed Mar 1 10:41:59 2017 +0100 $ Plugins: 201703010941 https://github.com/pharo-project/pharo-vm.git $
CoInterpreter * VMMaker.oscog-EstebanLorenzano.2136 uuid: 40534c32-ca6b-4e97-91ec-31d509e49b0c Mar  1 2017
StackToRegisterMappingCogit * VMMaker.oscog-EstebanLorenzano.2136 uuid: 40534c32-ca6b-4e97-91ec-31d509e49b0c Mar  1 2017
```

```
LGitCredentials class(Object)>>error:
[ :subclass | 
(subclass bindingOf: symbol)
	ifNotNil: [ ^ self
			error:
				symbol asString , ' is already used as a variable name in class '
					, subclass name ] ] in LGitCredentials class(Class)>>addClassVariable: in Block: [ :subclass | ...
OrderedCollection>>do:
LGitCredentials class(Class)>>addClassVariable:
LGitCredentials class(Class)>>addClassVarNamed:
LGitCredentials class(FFIExternalStructure class)>>defineFieldOffset:value:
[ :fieldName :type | 
offset := offset alignedTo: type typeAlignment.
self defineFieldOffset: fieldName value: offset + 1.
(defineBoolean and: [ fieldName isSymbol ])
	ifTrue: [ self defineFieldAccessorsFor: fieldName type: type ].
offset := offset + type typeSize.
externalStructureAlignment := externalStructureAlignment
	max: type typeAlignment ] in LGitCredentials class(FFIExternalStructure class)>>compileFields:withAccessors: in Block: [ :fieldName :type | ...
[ :each | aBlock value: each value: (self at: each) ] in OrderedDictionary>>keysAndValuesDo: in Block: [ :each | aBlock value: each value: (self at: each...etc...
OrderedDictionary>>keysDo:
OrderedDictionary>>keysAndValuesDo:
FFIExternalStructureFieldSpec>>fieldsAndTypesDo:
LGitCredentials class(FFIExternalStructure class)>>compileFields:withAccessors:
LGitCredentials class(ExternalStructure class)>>compileFields:
LGitCredentials class(ExternalStructure class)>>compileFields
LGitCredentials class(ExternalStructure class)>>compiledSpec
ExternalType>>newReferentClass:
ExternalType class>>newTypeNamed:force:
ExternalType class>>structTypeNamed:
FFIExternalStructureType>>externalType
FFIExternalStructureType(FFIExternalType)>>externalTypeWithArity
ByteSymbol(Symbol)>>value:
OrderedCollection>>collect:
LGitSafeFFICalloutMethodBuilder(FFICalloutMethodBuilder)>>createFFICalloutLiteralFromSpec:
LGitSafeFFICalloutMethodBuilder(FFICalloutMethodBuilder)>>generateFFICallout:spec:
LGitSafeFFICalloutMethodBuilder>>generateFFICallout:spec:
[ :builder | self generateFFICallout: builder spec: functionSpec ] in LGitSafeFFICalloutMethodBuilder(FFICalloutMethodBuilder)>>generateMethodFromSpec: in Block: [ :builder | self generateFFICallout: builder spec...etc...
IRBuilder class>>buildIR:
LGitSafeFFICalloutMethodBuilder(FFICalloutMethodBuilder)>>generateMethodFromSpec:
LGitSafeFFICalloutMethodBuilder(FFICalloutMethodBuilder)>>generate
LGitSafeFFICalloutMethodBuilder(FFICalloutMethodBuilder)>>build:
```

**Comment by demarey** [comment]
I was able to push with the latest VM. I just did 2 pushes.

**Comment by estebanlm** [comment]
btw, this is not real anymore :)
